### ISSUE TITLE
mikutterのdevelopブランチでmikutterが死ぬ

### ISSUE THREAD

**Issue by Petitsurume** [Petitsurume/mikutter_pnutio#7]
https://gist.github.com/Petitsurume/383178271774357f7309fbb79ad0ec07

**Comment by Na0ki** [comment]
前後のログをもう少しもらえるとわかるかもしれないです。
あと、死ぬタイミングとかその辺もわかるといいかも。

**Comment by Petitsurume** [comment]
#8 で解決
